### ISSUE TITLE
ValueError: cannot reindex from a duplicate axis from plot_distributions()

### ISSUE THREAD

**Issue by chenh38** [Baukebrenninkmeijer/table-evaluator#26] opened 2022-03-16 19:58 UTC
I have installed 1.3.2, and see this error when running table_evaluator.visual_evaluation()

--------------------------------------------------------------------------------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_15878/2454527378.py in <module>
----> 1 table_evaluator.visual_evaluation()

~/anaconda3/envs/gan/lib/python3.8/site-packages/table_evaluator/table_evaluator.py in visual_evaluation(self, save_dir, **kwargs)
    374             self.plot_mean_std()
    375             self.plot_cumsums()
--> 376             self.plot_distributions()
    377             self.plot_correlation_difference(**kwargs)
    378             self.plot_pca()

~/anaconda3/envs/gan/lib/python3.8/site-packages/table_evaluator/table_evaluator.py in plot_distributions(self, nr_cols, fname)
    155             if col not in self.categorical_columns:
    156                 plot_df = pd.DataFrame({col: self.real[col].append(self.fake[col]), 'kind': ['real'] * self.n_samples + ['fake'] * self.n_samples})
--> 157                 fig = sns.histplot(plot_df, x=col, hue='kind', ax=axes[i], stat='probability', legend=True)
    158                 axes[i].set_autoscaley_on(True)
    159             else:

~/anaconda3/envs/gan/lib/python3.8/site-packages/seaborn/distributions.py in histplot(data, x, y, hue, weights, stat, bins, binwidth, binrange, discrete, cumulative, common_bins, common_norm, multiple, element, fill, shrink, kde, kde_kws, line_kws, thresh, pthresh, pmax, cbar, cbar_ax, cbar_kws, palette, hue_order, hue_norm, color, log_scale, legend, ax, **kwargs)
   1460     if p.univariate:
   1461 
-> 1462         p.plot_univariate_histogram(
   1463             multiple=multiple,
   1464             element=element,

~/anaconda3/envs/gan/lib/python3.8/site-packages/seaborn/distributions.py in plot_univariate_histogram(self, multiple, element, fill, common_norm, common_bins, shrink, kde, kde_kws, color, legend, line_kws, estimate_kws, **plot_kws)
    398         if set(self.variables) - {"x", "y"}:
    399 
--> 400             all_data = self.comp_data.dropna()
    401 
    402             if common_bins:

~/anaconda3/envs/gan/lib/python3.8/site-packages/seaborn/_core.py in comp_data(self)
   1055                     orig = self.plot_data[var].dropna()
   1056                 comp_col = pd.Series(index=orig.index, dtype=float, name=var)
-> 1057                 comp_col.loc[orig.index] = pd.to_numeric(axis.convert_units(orig))
   1058 
   1059                 if axis.get_scale() == "log":

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexing.py in __setitem__(self, key, value)
    668 
    669         iloc = self if self.name == "iloc" else self.obj.iloc
--> 670         iloc._setitem_with_indexer(indexer, value)
    671 
    672     def _validate_key(self, key, axis: int):

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexing.py in _setitem_with_indexer(self, indexer, value)
   1790                 # setting for extensionarrays that store dicts. Need to decide
   1791                 # if it's worth supporting that.
-> 1792                 value = self._align_series(indexer, Series(value))
   1793 
   1794             elif isinstance(value, ABCDataFrame):

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexing.py in _align_series(self, indexer, ser, multiindex_indexer)
   1909             # series, so need to broadcast (see GH5206)
   1910             if sum_aligners == self.ndim and all(is_sequence(_) for _ in indexer):
-> 1911                 ser = ser.reindex(obj.axes[0][indexer[0]], copy=True)._values
   1912 
   1913                 # single indexer

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/series.py in reindex(self, index, **kwargs)
   4397     )
   4398     def reindex(self, index=None, **kwargs):
-> 4399         return super().reindex(index=index, **kwargs)
   4400 
   4401     def drop(

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   4459 
   4460         # perform the reindex on the axes
-> 4461         return self._reindex_axes(
   4462             axes, level, limit, tolerance, method, fill_value, copy
   4463         ).__finalize__(self, method="reindex")

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/generic.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   4479 
   4480             axis = self._get_axis_number(a)
-> 4481             obj = obj._reindex_with_indexers(
   4482                 {axis: [new_index, indexer]},
   4483                 fill_value=fill_value,

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/generic.py in _reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   4522 
   4523             # TODO: speed up on homogeneous DataFrame objects
-> 4524             new_data = new_data.reindex_indexer(
   4525                 index,
   4526                 indexer,

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/internals/managers.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy, consolidate)
   1274         # some axes don't allow reindexing with dups
   1275         if not allow_dups:
-> 1276             self.axes[axis]._can_reindex(indexer)
   1277 
   1278         if axis >= self.ndim:

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexes/base.py in _can_reindex(self, indexer)
   3287         # trying to reindex on an axis with duplicates
   3288         if not self.is_unique and len(indexer):
-> 3289             raise ValueError("cannot reindex from a duplicate axis")
   3290 
   3291     def reindex(self, target, method=None, level=None, limit=None, tolerance=None):

ValueError: cannot reindex from a duplicate axis

**Comment by peterson7773702** [comment] 2022-03-30 02:44
I aslo run table_evaluator.visual_evaluation() with the same issue. This is also encountered in the following case：https://medium.com/analytics-vidhya/a-step-by-step-guide-to-generate-tabular-synthetic-dataset-with-gans-d55fc373c8db.

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14412/2454527378.py in <module>
----> 1 table_evaluator.visual_evaluation()

c:\users\user\1.gans\1. gan_1\diabetes_research\table-evaluator-master\table_evaluator\table_evaluator.py in visual_evaluation(self, save_dir, **kwargs)
    374             self.plot_mean_std()
    375             self.plot_cumsums()
--> 376             self.plot_distributions()
    377             self.plot_correlation_difference(**kwargs)
    378             self.plot_pca()

...................

~\anaconda3\lib\site-packages\pandas\core\internals\managers.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy, consolidate, only_slice)
    668         # some axes don't allow reindexing with dups
    669         if not allow_dups:
--> 670             self.axes[axis]._validate_can_reindex(indexer)
    671 
    672         if axis >= self.ndim:

~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in _validate_can_reindex(self, indexer)
   3783         # trying to reindex on an axis with duplicates
   3784         if not self._index_as_unique and len(indexer):
-> 3785             raise ValueError("cannot reindex from a duplicate axis")
   3786 
   3787     def reindex(

ValueError: cannot reindex from a duplicate axis

**Comment by Baukebrenninkmeijer** [comment] 2022-04-06 09:36
@peterson7773702  @chenh38 
Hey Guys, thanks for reporting. Could you share your `pandas` and `table_evaluator` versions?

**Comment by Baukebrenninkmeijer** [comment] 2022-04-06 09:52
For both the 1.3.2 release as well as the latest dev commit, I have working examples and running tests. Could you share a minimal example where this error shows? 

FYI, i'm running:
`pandas`==1.4.1

**Comment by Baukebrenninkmeijer** [comment] 2022-04-06 09:57
This is also a duplicate issue of #25

**Comment by Tejaswini10062019** [comment] 2022-04-07 08:03
I am running 
Panda's version :1.4.1

**Comment by Tejaswini10062019** [comment] 2022-04-07 09:01
Dataset: https://archive.ics.uci.edu/ml/datasets/Early+stage+diabetes+risk+prediction+dataset.
from ctgan import CTGANSynthesizer
# Identifies all the discrete columns
discrete_columns = [
    'Gender',
    'Polyuria',
    'Polydipsia',
    'sudden weight loss',
    'weakness',
    'Polyphagia',
    'Genital thrush',
    'visual blurring',
    'Itching',
    'Irritability',
    'delayed healing',
    'partial paresis',
    'muscle stiffness',
    'Alopecia',
    'Obesity',
    'Outcome'
]

# Initiates the CTGANSynthesizer and call its fit method to pass in the table
 
ctgan = CTGANSynthesizer(epochs=50)
ctgan.fit(real_data, discrete_columns)

synthetic_data = ctgan.sample(520)
print(synthetic_data.head(5))

from table_evaluator import load_data, TableEvaluator

print(real_data.shape, synthetic_data.shape)
cat_cols = ['Outcome']
table_evaluator =  TableEvaluator(real_data, synthetic_data, cat_cols=cat_cols)

table_evaluator.visual_evaluation()

**Comment by Baukebrenninkmeijer** [comment] 2022-04-07 11:15
The dataset returns a Not Found error. Can you send me the exact file?

When I run this with the [official dataset](https://archive.ics.uci.edu/ml/datasets/Early+stage+diabetes+risk+prediction+dataset) it works fine. If possible, could you send a google colab link with a notebook and the file?

**Comment by Tejaswini10062019** [comment] 2022-04-07 17:50
https://colab.research.google.com/drive/1EKTiGy4Fx4PtIQOSBc_P2HnJv32Bofq0?usp=sharing
I used Iris Dataset in this code

**Comment by chenh38** [comment] 2022-04-07 19:05
I am using notebook and dataset below
notebook
https://github.com/fzhurd/fzwork/blob/master/medium/ganspost/test_gan_create_diabetic_data.ipynb
data
https://www.kaggle.com/uciml/pima-indians-diabetes-database?select=diabetes.csv

I am using pandas 1.1.3 and table-evaluator 1.3.?. I also tried to downgrade table-evaluator 1.2.2, but has the same error.
Today, I just upgrade pandas to 1.4.2, and table-evaluator 1.4.1, the error still persists

plot_df = pd.DataFrame({col: self.real[col].append(self.fake[col]), 'kind': ['real'] * self.n_samples + ['fake'] * self.n_samples})
/home/chenhaibin/anaconda3/envs/gan/lib/python3.8/site-packages/seaborn/_core.py:1057: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  comp_col.loc[orig.index] = pd.to_numeric(axis.convert_units(orig))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_364/2454527378.py in <module>
----> 1 table_evaluator.visual_evaluation()

~/anaconda3/envs/gan/lib/python3.8/site-packages/table_evaluator/table_evaluator.py in visual_evaluation(self, save_dir, **kwargs)
    374             self.plot_mean_std()
    375             self.plot_cumsums()
--> 376             self.plot_distributions()
    377             self.plot_correlation_difference(**kwargs)
    378             self.plot_pca()

~/anaconda3/envs/gan/lib/python3.8/site-packages/table_evaluator/table_evaluator.py in plot_distributions(self, nr_cols, fname)
    155             if col not in self.categorical_columns:
    156                 plot_df = pd.DataFrame({col: self.real[col].append(self.fake[col]), 'kind': ['real'] * self.n_samples + ['fake'] * self.n_samples})
--> 157                 fig = sns.histplot(plot_df, x=col, hue='kind', ax=axes[i], stat='probability', legend=True)
    158                 axes[i].set_autoscaley_on(True)
    159             else:

~/anaconda3/envs/gan/lib/python3.8/site-packages/seaborn/distributions.py in histplot(data, x, y, hue, weights, stat, bins, binwidth, binrange, discrete, cumulative, common_bins, common_norm, multiple, element, fill, shrink, kde, kde_kws, line_kws, thresh, pthresh, pmax, cbar, cbar_ax, cbar_kws, palette, hue_order, hue_norm, color, log_scale, legend, ax, **kwargs)
   1460     if p.univariate:
   1461 
-> 1462         p.plot_univariate_histogram(
   1463             multiple=multiple,
   1464             element=element,

~/anaconda3/envs/gan/lib/python3.8/site-packages/seaborn/distributions.py in plot_univariate_histogram(self, multiple, element, fill, common_norm, common_bins, shrink, kde, kde_kws, color, legend, line_kws, estimate_kws, **plot_kws)
    398         if set(self.variables) - {"x", "y"}:
    399 
--> 400             all_data = self.comp_data.dropna()
    401 
    402             if common_bins:

~/anaconda3/envs/gan/lib/python3.8/site-packages/seaborn/_core.py in comp_data(self)
   1055                     orig = self.plot_data[var].dropna()
   1056                 comp_col = pd.Series(index=orig.index, dtype=float, name=var)
-> 1057                 comp_col.loc[orig.index] = pd.to_numeric(axis.convert_units(orig))
   1058 
   1059                 if axis.get_scale() == "log":

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexing.py in __setitem__(self, key, value)
    714 
    715         iloc = self if self.name == "iloc" else self.obj.iloc
--> 716         iloc._setitem_with_indexer(indexer, value, self.name)
    717 
    718     def _validate_key(self, key, axis: int):

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexing.py in _setitem_with_indexer(self, indexer, value, name)
   1688             self._setitem_with_indexer_split_path(indexer, value, name)
   1689         else:
-> 1690             self._setitem_single_block(indexer, value, name)
   1691 
   1692     def _setitem_with_indexer_split_path(self, indexer, value, name: str):

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexing.py in _setitem_single_block(self, indexer, value, name)
   1927             # setting for extensionarrays that store dicts. Need to decide
   1928             # if it's worth supporting that.
-> 1929             value = self._align_series(indexer, Series(value))
   1930 
   1931         elif isinstance(value, ABCDataFrame) and name != "iloc":

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexing.py in _align_series(self, indexer, ser, multiindex_indexer)
   2089                 if obj.ndim == 2 and is_empty_indexer(indexer[0], ser._values):
   2090                     return ser._values.copy()
-> 2091                 ser = ser.reindex(obj.axes[0][indexer[0]], copy=True)._values
   2092 
   2093                 # single indexer

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/series.py in reindex(self, *args, **kwargs)
   4670                 )
   4671             kwargs.update({"index": index})
-> 4672         return super().reindex(**kwargs)
   4673 
   4674     @deprecate_nonkeyword_arguments(version=None, allowed_args=["self", "labels"])

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   4964 
   4965         # perform the reindex on the axes
-> 4966         return self._reindex_axes(
   4967             axes, level, limit, tolerance, method, fill_value, copy
   4968         ).__finalize__(self, method="reindex")

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/generic.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   4984 
   4985             axis = self._get_axis_number(a)
-> 4986             obj = obj._reindex_with_indexers(
   4987                 {axis: [new_index, indexer]},
   4988                 fill_value=fill_value,

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/generic.py in _reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   5030 
   5031             # TODO: speed up on homogeneous DataFrame objects (see _reindex_multi)
-> 5032             new_data = new_data.reindex_indexer(
   5033                 index,
   5034                 indexer,

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/internals/managers.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy, consolidate, only_slice, use_na_proxy)
    677         # some axes don't allow reindexing with dups
    678         if not allow_dups:
--> 679             self.axes[axis]._validate_can_reindex(indexer)
    680 
    681         if axis >= self.ndim:

~/anaconda3/envs/gan/lib/python3.8/site-packages/pandas/core/indexes/base.py in _validate_can_reindex(self, indexer)
   4105         # trying to reindex on an axis with duplicates
   4106         if not self._index_as_unique and len(indexer):
-> 4107             raise ValueError("cannot reindex on an axis with duplicate labels")
   4108 
   4109     def reindex(

ValueError: cannot reindex on an axis with duplicate labels

**Comment by Baukebrenninkmeijer** [comment] 2022-04-19 11:55
@chenh38 @Tejaswini10062019 Thanks for your patience. 

I at least know the problem currently, and have a temporary fix. The issue is with a change in `seaborn==0.11.2`. The library still works fine with `seaborn==0.11.1`, so if you downgrade to that using `pip install seaborn==0.11.1` you should be good. 

I'll try to see if I can fix the issue, but it might just be a problem with Seaborn over which I have no control. 

Let me know if this solution fixes the problem for now at least.

**Comment by chenh38** [comment] 2022-04-19 15:13
cool, it works after downgrade seaborn==0.11.1. thanks for the efforts. 

> @chenh38 @Tejaswini10062019 Thanks for your patience.
> 
> I at least know the problem currently, and have a temporary fix. The issue is with a change in `seaborn==0.11.2`. The library still works fine with `seaborn==0.11.1`, so if you downgrade to that using `pip install seaborn==0.11.1` you should be good.
> 
> I'll try to see if I can fix the issue, but it might just be a problem with Seaborn over which I have no control.
> 
> Let me know if this solution fixes the problem for now at least.

**Comment by andrey-orderby** [comment] 2022-06-17 08:21
I think, I have a way to solve this. 
I have come across the same problem, got exactly the error line "_core.py:1057: FutureWarning: reindexing ..." . The version of seaborn is 0.11.2
I had some dataframe _stat_ and I was trying to plot it using 
sns.lineplot(data = stat, x = '...', y = '...', hue = '...') 

All I had to do is to reindex my dataframe beforehand
stat.reset_index(drop = True, inplace = True)

I guess the problem was that the index of my dataframe _stat_ had duplicate values. This in turn may happen when you aggregate the data frame in a loop using pd.DataFrame.append() method. No wonder append is now deprecated and pd.concat is recommended instead.

**Comment by Baukebrenninkmeijer** [comment] 2023-01-02 22:23
Closing since the issue was solved.

**Closed by Baukebrenninkmeijer** 2023-01-02 22:23 UTC
Labels: bug
